### ISSUE TITLE
E117: Unknown function: VisualPut

### ISSUE THREAD

**Issue by hupfdule** [andymass/vim-visput#1]
When executing `p` on a visual selection I get the error

```
 E117: Unknown function: VisualPut
 ```

 This happens in vim 8.2 as well as in neovim 0.5.0.

 Therefore it does not work at all for me. Looking at the code I suspect that the `s:setup()` is not working correctly,, but I don't really understand what it does (or should do).

**Comment by andymass** [comment]
Thanks for your interest in the plugin.  I'm not sure why you're facing this issue, but I realized there's a compatibility problem in the code.  Let me know if it fixed it.

**Comment by hupfdule** [comment]
Basically: Yes, it does fix it.

But there is another problem now. I breaks the primary clipboard "a bit" in vim (but apparently not in neovim).

Usually I can visually select some code and press `"*p` for pasting over it with the content of the primary clipboard multiple times.

But with visput I can do it only once. After that the content of the primary clipboard is overwritten as soon as I visually select some text with the now selected text (therefore I can only paste the same text I have currently selected).

As this seems to happen only in vim and I use mainly neovim I don't care that much about the problem, but I think you should know about it ;-).

**Comment by andymass** [comment]
What is the value of `:set clipboard?` in either case (vim and neovim)?

**Comment by hupfdule** [comment]
That's interesting. I didn't know there is a difference, since both share the same configuration.

But in fact:

- vim: `clipboard=autoselect,exclude:cons\|linux`
- neovim: `clipboard=`

It seems that neovims clipboard integration is totally different from vim and doesn't even support the same settings.
I played around with it and found that the above mentioned problem even happens when starting vim with `--noplugins`. The option `autoselect` is the actual problem. And it seems to be on by default (as I haven't set it anywhere).

So this does not seem to be related to visput at all.

**Comment by andymass** [comment]
Thanks for the update!  I think this makes sense- with `autoselect` vim is going to overwrite the primary selection.
Closing then.
